# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac0618e25d5c457039acfa9f0b49d610742b876d9c938b6670a42a56652a688451a9a2bce0d077589152ee75f5d63f114f12a207ef502f99c26fdcd363e8562f

test:
  secret_key_base: 9276289b14c4285b9c372631f6e9938dcfd4316d7c023d897400dbc0c3d049f03535ff089b49db0d16ce36ae89eb8f36df4e6676afb4e86e83d32acc7b260295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
